# Generated by Django 4.2 on 2023-05-14 03:26

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="follow",
            name="user",
        ),
        migrations.RemoveField(
            model_name="profile",
            name="sex",
        ),
        migrations.AddField(
            model_name="follow",
            name="followed",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="followers",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="follow",
            name="follower",
            field=models.ForeignKey(
                default=0,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="following",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="follow",
            name="profile",
            field=models.ForeignKey(
                blank=True,
                default=None,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="follows",
                to="base.profile",
            ),
        ),
        migrations.AddField(
            model_name="profile",
            name="is_male",
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name="comment",
            name="comment_text",
            field=models.TextField(
                blank=True,
                max_length=300,
                validators=[
                    django.core.validators.MinValueValidator(
                        0,
                        message="At least one of comment_text, comment_image, or comment_video is required.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_text",
            field=models.TextField(
                blank=True,
                max_length=300,
                validators=[
                    django.core.validators.MinValueValidator(
                        0,
                        message="At least one of post_text, post_image, or post_video is required.",
                    )
                ],
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="comment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.comment",
            ),
        ),
        migrations.AlterField(
            model_name="vote",
            name="post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="base.post",
            ),
        ),
    ]
