# Generated by Django 4.2 on 2023-05-14 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_remove_follow_user_remove_profile_sex_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="post_text",
            field=models.TextField(
                blank=True,
                max_length=300,
                validators=[
                    django.core.validators.MinValueValidator(
                        "0",
                        message="At least one of post_text, post_image, or post_video is required.",
                    )
                ],
            ),
        ),
    ]
