# Generated by Django 4.2 on 2023-05-14 12:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0003_alter_post_post_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="comment_text",
            field=models.TextField(
                blank=True,
                max_length=300,
                validators=[
                    django.core.validators.MinValueValidator(
                        "0",
                        message="At least one of comment_text, comment_image, or comment_video is required.",
                    )
                ],
            ),
        ),
    ]
